name: Deploy Collectors

on:
  push:
    branches:
      - main
    paths:
      - 'collectors/**'
      - 'shared/**'
      - '.github/workflows/deploy.yml'
      - 'terraform/**'

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  REGISTRY_HOST: us-central1-docker.pkg.dev
  REPO_NAME: collectors
  # Added for Terraform Init
  TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}

      - name: 'Login to Artifact Registry'
        uses: 'docker/login-action@v3'
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - name: Build and push Google Workspace Docker image
        run: |
          IMAGE_PATH="${{ env.REGISTRY_HOST }}/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/google-workspace-collector"
          docker build -t $IMAGE_PATH:latest -f collectors/google_workspace/Dockerfile .
          docker push $IMAGE_PATH:latest

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: terraform
        run: |
          # Pass the bucket name dynamically so it's not hardcoded in the public repo
          terraform init -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}"

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
        env:
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_pubsub_topic_name: "defenda-event-ingest"
          TF_VAR_collectors: >
            {
              "google-workspace" = {
                "enabled"  = true,
                "schedule" = "0 * * * *",
                "env_vars" = {
                  "APPLICATION_NAMES" = "login,admin,token,drive"
                },
                "secret_mounts" = {
                  "GOOGLE_WORKSPACE_DELEGATED_ACCOUNT" = "google-workspace-admin-email"
                }
              }
            }
